# Generated by Django 5.2.10 on 2026-09-10 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_varified_email_emailverification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_varified_email',
            new_name='is_verified_email',
        ),
    ]
